from typing import Protocol, Literal

CategoryStatus = Literal["active", "inactive"]
ServiceStatus = Literal["active", "inactive"]

class AdminCatalogRepoPort(Protocol):
    async def list_categories(self) -> list[dict]: ...
    async def create_category(self, name: str, description: str) -> dict: ...
    async def update_category(self, cat_id: str, patch: dict) -> dict: ...
    async def delete_category(self, cat_id: str) -> None: ...
    async def set_category_status(self, cat_id: str, active: bool) -> dict: ...
