from typing import Protocol, Optional, List, Dict, Any

class AdminLocationRepo(Protocol):
    # Campus
    async def list_campus(self) -> List[Dict[str, Any]]: ...
    async def create_campus(self, name: str, address: str) -> Dict[str, Any]: ...
    async def update_campus(self, campus_id: str, name: Optional[str], address: Optional[str]) -> Dict[str, Any]: ...
    async def soft_delete_campus(self, campus_id: str) -> None: ...
    async def reactivate_campus(self, campus_id: str) -> Dict[str, Any]: ...

    # Buildings
    async def list_buildings(self, campus_id: Optional[str] = None) -> List[Dict[str, Any]]: ...
    async def create_building(self, name: str, campus_id: str) -> Dict[str, Any]: ...
    async def update_building(self, building_id: str, name: Optional[str], campus_id: Optional[str]) -> Dict[str, Any]: ...
    async def soft_delete_building(self, building_id: str) -> None: ...
    async def reactivate_building(self, building_id: str) -> Dict[str, Any]: ...

    # Rooms
    async def list_rooms(self, building_id: Optional[str] = None) -> List[Dict[str, Any]]: ...
    async def create_room(self, name: str, building_id: str, number: str, rtype: str, capacity: int) -> Dict[str, Any]: ...
    async def update_room(self, room_id: str, name: Optional[str], building_id: Optional[str],
                          number: Optional[str], rtype: Optional[str], capacity: Optional[int]) -> Dict[str, Any]: ...
    async def soft_delete_room(self, room_id: str) -> None: ...
    async def reactivate_room(self, room_id: str) -> Dict[str, Any]: ...
