from typing import Protocol, Optional, List
from app.domain.auth.asesor_perfil import AsesorPerfil, RegisterAdvisorRequest, AdvisorInfo, AdvisorPage

class AsesorPerfilRepo(Protocol):
    async def find_by_usuario_id(self, usuario_id: str) -> Optional[AsesorPerfil]: ...
    async def create_perfil(self, usuario_id: str) -> AsesorPerfil: ...
    async def ensure_perfil_exists(self, usuario_id: str) -> AsesorPerfil: ...
    async def ensure_user_is_asesor(self, user_id: str) -> None: ...
    async def list_advisors(self) -> List[AdvisorInfo]: ...
    async def list_advisors_page(self, *, page: int, limit: int, query: str | None = None, category_id: str | None = None, service_id: str | None = None) -> AdvisorPage: ...
    async def register_advisor(self, request: RegisterAdvisorRequest) -> AdvisorInfo: ...
    async def get_advisor_by_id(self, advisor_id: str) -> Optional[AdvisorInfo]: ...
    async def update_advisor_services(self, advisor_id: str, service_ids: List[str]) -> AdvisorInfo: ...
    async def delete_advisor(self, advisor_id: str) -> None: ...
