from typing import Protocol, Optional
from app.domain.auth.user import User

class UserRepo(Protocol):
    async def find_by_google_sub(self, sub: str) -> Optional[User]: ...
    async def find_by_email(self, email: str) -> Optional[User]: ...
    async def upsert_user_with_identity(self, *, email:str, name:str|None, sub:str,
                                        refresh_token:str|None) -> User: ...
    async def get_role_name(self, user_id: str) -> Optional[str]: ...