from typing import Protocol, Optional

class CachePort(Protocol):
    async def get(self, key: str) -> Optional[bytes]: ...
    async def set(self, key: str, value: bytes, ttl_seconds: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def acquire_lock(self, key: str, ttl_seconds: int = 10) -> bool: ...
    async def release_lock(self, key: str) -> None: ...