from typing import Protocol, Optional, TypedDict

class PendingCalendarEvent(TypedDict):
    asesoria_id: str
    cupo_id: str
    docente_email: str
    provider_event_id: str

class CalendarEventsRepo(Protocol):
    async def upsert_calendar_event(
        self,
        *,
        asesoria_id: str,
        organizer_usuario_id: str,
        calendar_event_id: str,
        html_link: str | None
    ) -> None: ...
    async def map_channel_owner(self, channel_id: str) -> Optional[str]: ...
    async def save_channel_owner(self, channel_id: str, usuario_id: str, resource_id: str|None=None) -> None: ...
    async def list_pending_for_organizer(self, organizer_usuario_id: str) -> list[PendingCalendarEvent]: ...
    async def mark_confirmed(self, asesoria_id: str) -> None: ...
    async def mark_rejected_and_free_slot(self, asesoria_id: str, cupo_id: str) -> None: ...
    async def mark_cancelled(self, asesoria_id: str) -> None: ...
    async def get_calendar_payload(self, asesoria_id: str) -> Optional[dict]: ...
    async def delete_asesoria_and_mark_cancelled(self, asesoria_id: str, cupo_id) -> None: ...
