from typing import Protocol, Optional, List
from app.domain.auth.docente_perfil import DocentePerfil, TeacherInfo, TeacherPage

class DocentePerfilRepo(Protocol):
    async def find_by_usuario_id(self, usuario_id: str) -> Optional[DocentePerfil]: ...
    async def create_perfil(self, usuario_id: str) -> DocentePerfil: ...
    async def ensure_perfil_exists(self, usuario_id: str) -> DocentePerfil: ...
    async def ensure_user_is_docente(self, user_id: str) -> None: ...
    async def list_teachers(self) -> List[TeacherInfo]: ...
    async def list_teachers_page(self, *, page: int, limit: int, query: str | None = None) -> TeacherPage: ...
    async def get_teacher_by_id(self, teacher_id: str) -> Optional[TeacherInfo]: ...
    async def update_teacher(self, teacher_id: str, *, name: str | None, email: str | None, active: bool | None) -> TeacherInfo: ...
    async def delete_teacher(self, teacher_id: str) -> None: ...
