from typing import Protocol, Optional
from app.domain.auth.docente_perfil import DocentePerfil

class DocentePerfilRepo(Protocol):
    async def find_by_usuario_id(self, usuario_id: str) -> Optional[DocentePerfil]: ...
    async def create_perfil(self, usuario_id: str) -> DocentePerfil: ...
    async def ensure_perfil_exists(self, usuario_id: str) -> DocentePerfil: ...