from typing import Any, Dict, List, Protocol

class MCPPort(Protocol):
    async def list_tools_openai_schema(self) -> List[Dict[str, Any]]: ...
    async def call_tool(self, name: str, args: Dict[str, Any]) -> Dict[str, Any]: ...