from typing import Protocol, Dict

class GoogleOAuthPort(Protocol):
    async def exchange_code(self, code:str, redirect_uri:str) -> Dict: ...
    async def userinfo(self, access_token:str) -> Dict: ...