from typing import Protocol, Optional, Iterable
from datetime import datetime

class SlotsRepo(Protocol):
    async def get_create_slots_data(self) -> dict: ...
    async def resolve_asesor_id(self, usuario_id: str) -> Optional[str]: ...
    async def get_servicio_minutes(self, servicio_id: str) -> int: ...
    async def ensure_asesor_puede_dicto_servicio(self, asesor_id: str, servicio_id: str) -> bool: ...
    async def find_conflicting_slots(
        self, recurso_id: str, periods: Iterable[tuple[datetime, datetime]],
    ) -> list[tuple[str, datetime, datetime]]: ...
    async def find_conflicting_slots_for_advisor(
        self, asesor_id: str, periods: Iterable[tuple[datetime, datetime]],
    ) -> list[tuple[str, datetime, datetime]]: ...
    async def bulk_insert_cupos(
        self, rows: Iterable[tuple[str, str, Optional[str], datetime, datetime, str | None]]
    ) -> tuple[int, int]: ...
