from typing import Protocol, Optional

class TelegramRepoPort(Protocol):
    async def link_telegram( self, token: str, telegram_user_id: int, chat_id: int, username: str | None, ) -> bool: ...
    async def find_user_id_by_telegram(self, telegram_user_id: int) -> Optional[str]: ...
