from typing import Protocol, Optional, Dict, Any, List, Tuple

class TelegramPort(Protocol):
    async def send_message(self, chat_id: int, text: str, reply_markup: Optional[Dict[str, Any]] = None) -> None: ...
    def inline_kb(self, rows: List[Tuple[str, str]]) -> Dict[str, Any]: ...
